### ISSUE TITLE
Small images bug

### ISSUE THREAD

**Issue by ed-mejia** [brynbodayle/BABCropperView#1]
Hi there, this lib is by far one of the best I found after a long time of surfing internet.

However there is a small detail when select small images using a particular crop size:

I'm using crop size 720 * 240 and I'm using this image: 
http://www.thetechchat.com/wp-content/uploads/2012/08/Microsoft-Logo.jpg you can download it from safari on simulator.

when prompted to pick it displays the picture like this : 
<img width="487" alt="screen shot 2015-07-07 at 11 00 45 pm" src="https://cloud.githubusercontent.com/assets/7431094/8546543/1488052e-24fc-11e5-8858-2ebcd0c83521.png"> 

which is ok like that because the user might not want to scale it, and just when you tap crop... this happen

<img width="487" alt="screen shot 2015-07-07 at 11 00 51 pm" src="https://cloud.githubusercontent.com/assets/7431094/8546566/3a1dc4f4-24fc-11e5-8401-76820ec656ef.png">

1) Is there a way to keep it centered and not aligned to the right?
2) Is there is a way to keep the background transparent? not black or at least white?

Cheers!.

**Comment by brynbodayle** [comment]
Thanks for the feedback Edinson.

I've fixed the alignment issue and added support for transparent images. To allow transparent images in export just set the following property to `YES` like so:

```self.cropperView.leavesUnfilledRegionsTransparent = YES```


Let me know if you have any additional questions or issues.

cc8dbeef212c545e6a1fa1f7163678d4e8a0cbe0

**Comment by ed-mejia** [comment]
Awesome works really great, thanks :+1:

**Comment by djbrooks111** [comment]
@brynbodayle Nice pod! I am encountering the same issue as @ed-mejia because CocoaPods doesn't see your 0.3.2 version. Could you fix this so that you are providing the latest Pod? Also, sorry to go off a closed issue, but is there anyway to have the image start off fully scaled to the size of the view?

**Comment by brynbodayle** [comment]
@djbrooks111 Ah, whoops. Just pushed the version 0.3.2. Thanks for letting me know about that.

Hmm, what exactly do you mean my fully scaled to the size of the view? The image being scaled to fill up the entire view or the image being scaled to be completely visible within the view? (Feel free to create a new issue with your response).

**Comment by djbrooks111** [comment]
@brynbodayle Thanks for pushing 0.3.2!

So for my issue, it is exactly what @ed-mejia has posted here, in that when the cropper view is first shown, the image is within the crop box (https://cloud.githubusercontent.com/assets/7431094/8546543/1488052e-24fc-11e5-8858-2ebcd0c83521.png). So my question is how can I make it so that the image that I want cropped is either the same size as the screen, or the image's original size.

**Comment by brynbodayle** [comment]
Same width or same height as the screen? You want it to fill the screen completely?

**Comment by djbrooks111** [comment]
Nevermind, the issue was the image was too small, it works just fine :)
